figure(8);
plot(t,x,t,xg);
legend('x','xg');
figure(9);
plot(t,y,t,yg);
legend('y','yg');
figure(10);
plot(t,abs(fai),t,abs(faig));
legend('fai','faig');
figure(11);
plot(t,u,'b',t,ug,'r:','linewidth',2.5);
legend('u','u_{obs}');
figure(12);
plot(t,v,'b',t,vg,'r:','linewidth',2.5);
legend('v','v_{obs}');
figure(13);
plot(t,r,'b',t,rg,'r:','linewidth',2.5);
legend('r','r_{obs}');
figure(14);
plot(t,u-ug,'b',t,v-vg,'g--',t,r-rg,'r:','linewidth',2.5);
legend('¹Û²âÎó²îu','¹Û²âÎó²îv','¹Û²âÎó²îr');
figure(15);
subplot(311);
plot(t,u,'r',t,ug,'b:','linewidth',2.5);
legend('u','u_{obs}');
subplot(312);
plot(t,v,'r',t,vg,'b:','linewidth',2.5);
legend('v','v_{obs}');
subplot(313);
plot(t,r,'r',t,rg,'b:','linewidth',2.5);
legend('r','r_{obs}');
figure(16);
subplot(311);
plot(t,Dfu,'r',t,Dfug,'b:','linewidth',2.5);
% plot(t,dfu,'r',t,dfu1,'b:','linewidth',2.5);
legend('\DeltaF_u','\DeltaF_u_{obs}');
% legend('\DeltaF_u','\DeltaF_u±Æ½üÖµ');
subplot(312);
plot(t,Dfv,'r',t,Dfvg,'b:','linewidth',2.5);
% plot(t,dfv,'r',t,dfv1,'b:','linewidth',2.5);
legend('\DeltaF_v','\DeltaF_v_{obs}');
subplot(313);
plot(t,Dfr,'r',t,Dfrg,'b:','linewidth',2.5);
% plot(t,dfr,'r',t,dfr1,'b:','linewidth',2.5);
legend('\DeltaF_r','\DeltaF_r_{obs}');
figure(17);
plot(t,Dfu-Dfug,'b',t,Dfv-Dfvg,'g--',t,Dfr-Dfrg,'r:','linewidth',2.5);
legend('×ÜÈÅ¶¯Îó²îu','×ÜÈÅ¶¯Îó²îv','×ÜÈÅ¶¯Îó²îr');
% figure(14);
% plot(t,x-x_b);
% legend('Îó²îx_b');
% figure(15);
% plot(t,y-y_b);
% legend('Îó²îy_b');
% figure(16);
% plot(t,fai-fai_b);
% legend('Îó²îfai_b');
% figure(17);
% plot(t,u-u_b);
% legend('Îó²îu_b');
% figure(18);
% plot(t,v-v_b);
% legend('Îó²îv_b');
% figure(19);
% plot(t,r-r_b);
% legend('Îó²îr_b');