close all;

figure(1);
plot(x,y,'--',xd,yd,'r','linewidth',2.5);
% plot(y,x,'--',yd,xd,'r','linewidth',2);
legend('实际轨迹','参考轨迹');
xlabel('x/m');
ylabel('y/m');

figure(2);
subplot(311);
plot(t,xd,'r',t,x,'b:','linewidth',2.5);
legend('x_d','x');
% xlabel('t/s');
ylabel('x/m');
subplot(312);
plot(t,yd,'r',t,y,'b:','linewidth',2.5);
legend('y_d','y');
% xlabel('t/s');
ylabel('y/m');
subplot(313);
plot(t,abs(fai),'linewidth',2.5);
legend('\psi');
xlabel('t/s');
ylabel('\psi/rad');

figure(3);
subplot(311);
plot(t,u,'linewidth',2.5);
% legend('u');
% xlabel('t/s');
ylabel('u/(m/s)');
subplot(312);
plot(t,v,'linewidth',2.5);
% legend('v');
% xlabel('t/s');
ylabel('v/(m/s)');
subplot(313);
plot(t,r,'linewidth',2.5);
legend('r');
xlabel('t/s');
ylabel('r/(rad/s)');

figure(4);
subplot(211);
plot(t,xe,'linewidth',2.5);
% legend('x_e');
xlabel('t/s');
ylabel('x_e/m');
subplot(212);
plot(t,ye,'linewidth',2.5);
% legend('y_e');
xlabel('t/s');
ylabel('y_e/m');

figure(5);
subplot(211);
plot(t,ue,'linewidth',2.5);
legend('u_e');
xlabel('t/s');
ylabel('u_e/(m/s)');
subplot(212);
plot(t,ve,'linewidth',2.5);
legend('v_e');
xlabel('t/s');
ylabel('v_e/(m/s)');

figure(6);
subplot(211);
plot(t,xd,t,x,'r:','linewidth',2.5);
legend('x_{d}','x');
subplot(212);
plot(t,yd,t,y,'r:','linewidth',2.5);
legend('y_{d}','y');
xlabel('t/s');

figure(7);
subplot(211);
plot(t,taou,'r','linewidth',2.5);
legend('\tau_u');
xlabel('t/s','Interpreter','tex','FontSize',20);
ylabel('\tau_u/N');
subplot(212);
plot(t,taor,'linewidth',2.5);
legend('\tau_r');
xlabel('t/s','Interpreter','tex','FontSize',20);
ylabel('\tau_r/Nm');

figure(8);
subplot(211);
plot(t,(twu),':',t,Twu,'r','linewidth',2.5);
legend('\tau_{wu}','\tau_{wu}估计值');
xlabel('t/s','Interpreter','tex','FontSize',20);
% ylabel('$\hat{\tau_{wu}}$','Interpreter','latex','FontSize',16);
subplot(212);
plot(t,(twr),':',t,Twr,'r','linewidth',2.5);
legend('\tau_{wr}','\tau_{wr}估计值');
xlabel('t/s','Interpreter','tex','FontSize',20);
% ylabel('$\hat{\tau_{wr}}$','Interpreter','latex','FontSize',16);

figure(9);
subplot(211);
plot(t,FU,t,FU1,'r:','linewidth',2.5);
% legend('\DeltaF_u','\DeltaF_u逼近值');
legend('F_u','F_u逼近值');
xlabel('t/s','Interpreter','tex','FontSize',20);
subplot(212);
plot(t,FR,t,FR1,'r:','linewidth',2.5);
% legend('\DeltaF_r','\DeltaF_r逼近值');
legend('F_r','F_r逼近值');
xlabel('t/s','Interpreter','tex','FontSize',20);

figure(10);
subplot(211);
plot(t,FU-FU1,'r:');
subplot(212);
plot(t,FR-FR1,'r:');

figure(11);
subplot(211);
plot(t,FU1,t,fu,'r:','linewidth',2.5);
% legend('\DeltaF_u','\DeltaF_u逼近值');
legend('F_u逼近值','F_u滤波值');
xlabel('t/s','Interpreter','tex','FontSize',20);
subplot(212);
plot(t,FR1,t,fr,'r:','linewidth',2.5);
% legend('\DeltaF_r','\DeltaF_r逼近值');
legend('F_r逼近值','F_r滤波值');
xlabel('t/s','Interpreter','tex','FontSize',20);

figure(12);
subplot(211);
plot(t,FU,t,fu,'r:','linewidth',2.5);
% legend('\DeltaF_u','\DeltaF_u逼近值');
legend('F_u','F_u滤波值');
xlabel('t/s','Interpreter','tex','FontSize',20);
subplot(212);
plot(t,FR,t,fr,'r:','linewidth',2.5);
% legend('\DeltaF_r','\DeltaF_r逼近值');
legend('F_r','F_r滤波值');
xlabel('t/s','Interpreter','tex','FontSize',20);